#!/bin/bash

[ "`md5 -q .aliases`" = "`md5 -q ~/.aliases`" ] && echo ".aliases is good" || echo ".aliases is mismatched"
[ "`md5 -q .bash_profile`" = "`md5 -q ~/.bash_profile`" ] && echo ".bash_profile is good" || echo ".bash_profile is mismatched"
[ "`md5 -q .bash_prompt`" = "`md5 -q ~/.bash_prompt`" ] && echo ".bash_prompt is good" || echo ".bash_prompt is mismatched"
[ "`md5 -q .bashrc`" = "`md5 -q ~/.bashrc`" ] && echo ".bashrc is good" || echo ".bashrc is mismatched"
[ "`md5 -q .brew`" = "`md5 -q ~/.brew`" ] && echo ".brew is good" || echo ".brew is mismatched"
[ "`md5 -q .exports`" = "`md5 -q ~/.exports`" ] && echo ".exports is good" || echo ".exports is mismatched"
[ "`md5 -q .functions`" = "`md5 -q ~/.functions`" ] && echo ".functions is good" || echo ".functions is mismatched"
[ "`md5 -q .gitattributes`" = "`md5 -q ~/.gitattributes`" ] && echo ".gitattributes is good" || echo ".gitattributes is mismatched"
[ "`md5 -q .gitconfig`" = "`md5 -q ~/.gitconfig`" ] && echo ".gitconfig is good" || echo ".gitconfig is mismatched"
[ "`md5 -q .gitignore`" = "`md5 -q ~/.gitignore`" ] && echo ".gitignore is good" || echo ".gitignore is mismatched"
[ "`md5 -q .gvimrc`" = "`md5 -q ~/.gvimrc`" ] && echo ".gvimrc is good" || echo ".gvimrc is mismatched"
[ "`md5 -q .inputrc`" = "`md5 -q ~/.inputrc`" ] && echo ".inputrc is good" || echo ".inputrc is mismatched"
[ "`md5 -q .osx`" = "`md5 -q ~/.osx`" ] && echo ".osx is good" || echo ".osx is mismatched"
[ "`md5 -q .screenrc`" = "`md5 -q ~/.screenrc`" ] && echo ".screenrc is good" || echo ".screenrc is mismatched"
[ "`md5 -q .vimrc`" = "`md5 -q ~/.vimrc`" ] && echo ".vimrc is good" || echo ".vimrc is mismatched"
[ "`md5 -q .wgetrc`" = "`md5 -q ~/.wgetrc`" ] && echo ".wgetr is good" || echo ".wgetr is mismatched"